//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAME()
        {
            this.USER_GAME = new HashSet<USER_GAME>();
        }
    
        public int GAME_ID { get; set; }
        public string NAME { get; set; }
        public decimal PRICE { get; set; }
        public System.DateTime PDATE { get; set; }
        public string PUBLISHER { get; set; }
        public string SIZE { get; set; }
        public string GAME_PLATFORM { get; set; }
        public string TYPE { get; set; }
        public string GAME_ADDRESS { get; set; }
        public string DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_GAME> USER_GAME { get; set; }
    }
}
