//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_GAME
    {
        public int CONTROL_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> GAME_ID { get; set; }
    
        public virtual GAME GAME { get; set; }
        public virtual USER USER { get; set; }
    }
}
